// Import JavaScript's fs library (used to read and write text files)
const fs = require('fs')


/* 
LETS CREATE SOME ERRORS SO WE CAN LEARN HOW TO READ AND UNDERSTAND ERRORS- USE NODE DOCUMENTATION

EVERY ERROR HAS: ERROR CODE, ERROR MESSAGE

*/ 


// const someFile = require("./someFile")


// fs.writeFile("./wazzaap", "hello world", function(err) {
//   if(err) {
//     console.log("Error writing file: ", err);
//   } else {
//     console.log("File written successfully!");
//   }
// })



// EXAMPLE OF SYSTEM ERROR: ATTEMPTING TO READ FROM A FILE THAT DOES NOT EXIST IN THIS SYSTEM.
// const content = fs.readFileSync("wazzaap")
// console.log(content.toString())


// fs.mkdirSync('temp_dir');
//SYNTAX ERRORS: WHEN JAVASCRIPT GRAMMAER (SYNTAX) RULES ARE BROKEN

//TYPE ERRORS: WHEN YOU MISUSE A DATATYPE AS IF IT WAS ANOTHER DATA TYPE
// console.log([1,2,3].length)
//ASSERTION ERRORS: ERRORS GENERATED BY TESTS WHEN ASSERTING: "expect(actual).to.equal(expected)"